# The root route on which each incoming alert enters.
route:
  group_by: [cluster, alertname]
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 5s
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 4h

  # A default receiver
  receiver: admins-receiver

  routes:
    - match:
        alertname: PrometheusAlertmanagerE2eDeadManSwitch
      routes:
        - receiver: noop

receivers:
- name: noop
- name: admins-receiver
  webhook_configs:
    - url: 'http://matrix-alertmanager:3000/alerts?secret={{ alertmanager_matrix_alertmanager_secret }}'
